version: '3'
services:
  strapi:
    image: strapi/strapi
    restart: always
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: api.domain.com
      VIRTUAL_PORT: 1337
      LETSENCRYPT_HOST: api.domain.com
      LETSENCRYPT_EMAIL: admin@domain.com
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: 'false'
    volumes:
      - ./app:/srv/app
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - '1337:1337'
    depends_on:
      - mysql
    networks:
      - web
      - database

  mysql:
    image: mariadb
    volumes:
      - domain-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
    networks:
      - database

  phpmyadmin:
    image: phpmyadmin
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - mysql
    networks:
      - web
      - database
    environment:
      VIRTUAL_HOST: pma.domain.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: pma.domain.com
      LETSENCRYPT_EMAIL: admin@domain.com
      PMA_HOST: mysql
# Auto authenticate USER_DB      PMA_USER: root
# Auto authenticate USER_PASSWORD     PMA_PASSWORD: strapi

volumes:
  domain-strapi-data:
  domain-db-data:

networks:
  database:
  web:
    external: true
